[package]
name = "kamilata"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p = {version="0.49", features=["kad", "ping", "noise", "yamux", "mplex"]}
tokio = {version="1.19", features=["full"]}
futures = "0.3"
protocol = "3.2"
protocol-derive = "3.2"
unsigned-varint = "0.7"
asynchronous-codec = "0.6.0"
