name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/rust.yml') }}
    - name: Install protoc
      run: sudo apt install protobuf-compiler
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Run expensive tests
      run: cargo test --release -- --ignored
